apiVersion: apps/v1
kind: Deployment
metadata:
  name: department
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      serviceAccountName: microservices-sa
      containers:
      - name: department
        image: department:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongodb:27017/departmentdb
---
apiVersion: v1
kind: Service
metadata:
  name: department
spec:
  selector:
    app: department
  ports:
  - port: 8082
    targetPort: 8082
