apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
    spec:
      serviceAccountName: microservices-sa
      containers:
      - name: employee
        image: employee:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongodb:27017/employeedb
---
apiVersion: v1
kind: Service
metadata:
  name: employee
spec:
  selector:
    app: employee
  ports:
  - port: 8083
    targetPort: 8083
